;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        comint-delchar-or-maybe-eof
        elpy-nav-backward-indent
        elpy-nav-forward-indent
        ess-smart-comma
        ess-yank
        helm-M-x
        indent-for-tab-command
        kill-region
        markdown-outdent-or-delete
        undo-tree-visualize
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-pound
        iedit-switch-to-mc-mode
        ))
