;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        elpy-nav-backward-indent
        elpy-nav-forward-indent
        ess-smart-comma
        indent-for-tab-command
        markdown-outdent-or-delete
        undo-tree-visualize
        ))

(setq mc/cmds-to-run-once
      '(
        iedit-switch-to-mc-mode
        ))
